version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: "no"
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping')\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  calculator:
    build: .
    container_name: calculator
    restart: "no"
    env_file:
      - .env
    environment:
      MONGO_URI: ${MONGO_URI}
      NODE_ENV: ${NODE_ENV:-development}
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"
    depends_on:
      mongo:
        condition: service_healthy
    volumes:
      - ./logs:/usr/src/app/logs

volumes:
  mongo-data:
