apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual   # matches mongo-pv.yaml
  resources:
    requests:
      storage: 1Gi
