apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
  namespace: calculator
  labels:
    app: mongo
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo   # GKE default block storage
  resources:
    requests:
      storage: 5Gi
