apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice
spec:
  selector:
    app: calculator
  type: NodePort
  ports:
    - protocol: TCP
      port: 3000           # Internal service port
      targetPort: 3000     # Port exposed by the container
      nodePort: 30080      #fixed external port 
