apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
