apiVersion: v1
kind: Service
metadata:
  name: calculator-microservice
  namespace: calculator
  labels:
    app: calculator
spec:
  selector:
    app: calculator
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80          # external port
      targetPort: 3000  # app container port
