name: CI

on:
  push:
    branches: [ main ]
    paths:
      - "calculator.js"
      - "package.json"
      - "package-lock.json"
      - ".github/workflows/ci.yml"
  pull_request:
    branches: [ main ]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (production)
        run: npm ci

      - name: Run tests (if present)
        run: |
          if npm run | grep -q " test"; then
            npm test
          else
            echo "No test script defined. Skipping."
          fi
